/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IntegrationRouteImport } from './routes/integration'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as SamplesRouteImport } from './routes/samples'
import { Route as AdminAssetsRouteImport } from './routes/admin.assets'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PortalAccountRouteImport } from './routes/portal.account'
import { Route as PortalCatalogRouteImport } from './routes/portal.catalog'
import { Route as PortalInvoicesRouteImport } from './routes/portal.invoices'
import { Route as PortalOrdersRouteImport } from './routes/portal.orders'
import { Route as PortalPriceBookRouteImport } from './routes/portal.price-book'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as ApiPublicSiteAssetSplatRouteImport } from './routes/api/public/site-asset.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationRoute = IntegrationRouteImport.update({
  id: '/integration',
  path: '/integration',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const SamplesRoute = SamplesRouteImport.update({
  id: '/samples',
  path: '/samples',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAssetsRoute = AdminAssetsRouteImport.update({
  id: '/admin/assets',
  path: '/admin/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAccountRoute = PortalAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => PortalRoute,
} as any)
const PortalCatalogRoute = PortalCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => PortalRoute,
} as any)
const PortalInvoicesRoute = PortalInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => PortalRoute,
} as any)
const PortalOrdersRoute = PortalOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => PortalRoute,
} as any)
const PortalPriceBookRoute = PortalPriceBookRouteImport.update({
  id: '/price-book',
  path: '/price-book',
  getParentRoute: () => PortalRoute,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSiteAssetSplatRoute = ApiPublicSiteAssetSplatRouteImport.update({
  id: '/api/public/site-asset/$',
  path: '/api/public/site-asset/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/catalog': typeof CatalogRoute
  '/contact': typeof ContactRoute
  '/integration': typeof IntegrationRoute
  '/portal': typeof PortalRouteWithChildren
  '/samples': typeof SamplesRoute
  '/admin/assets': typeof AdminAssetsRoute
  '/portal/account': typeof PortalAccountRoute
  '/portal/catalog': typeof PortalCatalogRoute
  '/portal/invoices': typeof PortalInvoicesRoute
  '/portal/orders': typeof PortalOrdersRoute
  '/portal/price-book': typeof PortalPriceBookRoute
  '/product/$id': typeof ProductIdRoute
  '/portal/': typeof PortalIndexRoute
  '/api/public/site-asset/$': typeof ApiPublicSiteAssetSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/catalog': typeof CatalogRoute
  '/contact': typeof ContactRoute
  '/integration': typeof IntegrationRoute
  '/samples': typeof SamplesRoute
  '/admin/assets': typeof AdminAssetsRoute
  '/portal/account': typeof PortalAccountRoute
  '/portal/catalog': typeof PortalCatalogRoute
  '/portal/invoices': typeof PortalInvoicesRoute
  '/portal/orders': typeof PortalOrdersRoute
  '/portal/price-book': typeof PortalPriceBookRoute
  '/product/$id': typeof ProductIdRoute
  '/portal': typeof PortalIndexRoute
  '/api/public/site-asset/$': typeof ApiPublicSiteAssetSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/catalog': typeof CatalogRoute
  '/contact': typeof ContactRoute
  '/integration': typeof IntegrationRoute
  '/portal': typeof PortalRouteWithChildren
  '/samples': typeof SamplesRoute
  '/admin/assets': typeof AdminAssetsRoute
  '/portal/account': typeof PortalAccountRoute
  '/portal/catalog': typeof PortalCatalogRoute
  '/portal/invoices': typeof PortalInvoicesRoute
  '/portal/orders': typeof PortalOrdersRoute
  '/portal/price-book': typeof PortalPriceBookRoute
  '/product/$id': typeof ProductIdRoute
  '/portal/': typeof PortalIndexRoute
  '/api/public/site-asset/$': typeof ApiPublicSiteAssetSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/catalog'
    | '/contact'
    | '/integration'
    | '/portal'
    | '/samples'
    | '/admin/assets'
    | '/portal/account'
    | '/portal/catalog'
    | '/portal/invoices'
    | '/portal/orders'
    | '/portal/price-book'
    | '/product/$id'
    | '/portal/'
    | '/api/public/site-asset/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/catalog'
    | '/contact'
    | '/integration'
    | '/samples'
    | '/admin/assets'
    | '/portal/account'
    | '/portal/catalog'
    | '/portal/invoices'
    | '/portal/orders'
    | '/portal/price-book'
    | '/product/$id'
    | '/portal'
    | '/api/public/site-asset/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/catalog'
    | '/contact'
    | '/integration'
    | '/portal'
    | '/samples'
    | '/admin/assets'
    | '/portal/account'
    | '/portal/catalog'
    | '/portal/invoices'
    | '/portal/orders'
    | '/portal/price-book'
    | '/product/$id'
    | '/portal/'
    | '/api/public/site-asset/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CatalogRoute: typeof CatalogRoute
  ContactRoute: typeof ContactRoute
  IntegrationRoute: typeof IntegrationRoute
  PortalRoute: typeof PortalRouteWithChildren
  SamplesRoute: typeof SamplesRoute
  AdminAssetsRoute: typeof AdminAssetsRoute
  ProductIdRoute: typeof ProductIdRoute
  ApiPublicSiteAssetSplatRoute: typeof ApiPublicSiteAssetSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integration': {
      id: '/integration'
      path: '/integration'
      fullPath: '/integration'
      preLoaderRoute: typeof IntegrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/samples': {
      id: '/samples'
      path: '/samples'
      fullPath: '/samples'
      preLoaderRoute: typeof SamplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/assets': {
      id: '/admin/assets'
      path: '/admin/assets'
      fullPath: '/admin/assets'
      preLoaderRoute: typeof AdminAssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/account': {
      id: '/portal/account'
      path: '/account'
      fullPath: '/portal/account'
      preLoaderRoute: typeof PortalAccountRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/catalog': {
      id: '/portal/catalog'
      path: '/catalog'
      fullPath: '/portal/catalog'
      preLoaderRoute: typeof PortalCatalogRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/invoices': {
      id: '/portal/invoices'
      path: '/invoices'
      fullPath: '/portal/invoices'
      preLoaderRoute: typeof PortalInvoicesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/orders': {
      id: '/portal/orders'
      path: '/orders'
      fullPath: '/portal/orders'
      preLoaderRoute: typeof PortalOrdersRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/price-book': {
      id: '/portal/price-book'
      path: '/price-book'
      fullPath: '/portal/price-book'
      preLoaderRoute: typeof PortalPriceBookRouteImport
      parentRoute: typeof PortalRoute
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/site-asset/$': {
      id: '/api/public/site-asset/$'
      path: '/api/public/site-asset/$'
      fullPath: '/api/public/site-asset/$'
      preLoaderRoute: typeof ApiPublicSiteAssetSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PortalRouteChildren {
  PortalAccountRoute: typeof PortalAccountRoute
  PortalCatalogRoute: typeof PortalCatalogRoute
  PortalInvoicesRoute: typeof PortalInvoicesRoute
  PortalOrdersRoute: typeof PortalOrdersRoute
  PortalPriceBookRoute: typeof PortalPriceBookRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalAccountRoute: PortalAccountRoute,
  PortalCatalogRoute: PortalCatalogRoute,
  PortalInvoicesRoute: PortalInvoicesRoute,
  PortalOrdersRoute: PortalOrdersRoute,
  PortalPriceBookRoute: PortalPriceBookRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CatalogRoute: CatalogRoute,
  ContactRoute: ContactRoute,
  IntegrationRoute: IntegrationRoute,
  PortalRoute: PortalRouteWithChildren,
  SamplesRoute: SamplesRoute,
  AdminAssetsRoute: AdminAssetsRoute,
  ProductIdRoute: ProductIdRoute,
  ApiPublicSiteAssetSplatRoute: ApiPublicSiteAssetSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
