/**
 * Taral product catalog for the Taral Direct prototype.
 *
 * SPECIFICATIONS ARE REAL. Sizes, neck finishes, max fill capacities,
 * dimensions, case counts, case weights, pallet quantities, freight classes,
 * base item codes, stocking status and minimum order quantities are
 * transcribed from Taral's published product documents (product one-sheet,
 * product line & style illustrations, and the stocking program pages of the
 * August 2026 distributor list).
 *
 * PRICES ARE NOT REAL. Taral's distributor pricing is confidential and is
 * deliberately excluded. Every price in this prototype is generated by the
 * invented `illustrativePrice` helper below and is labeled as demo data
 * wherever it appears.
 */

export type Category =
  | "Regular Wall Jars"
  | "Thick Wall Jars"
  | "Double Wall Jars"
  | "Lids & Closures"
  | "Discs & Dust Covers"
  | "Add-ons";

/**
 * Stocking status from the published stocking program.
 * - "In stock": marked as a stock item, 1 case minimum (small order fee may apply).
 * - "Overrun — call": not a stock item, but overrun inventory may exist.
 * - "Made to order": non-stock; the item's MOQ or setup fee applies.
 */
export type StockStatus = "In stock" | "Overrun — call" | "Made to order";

export type StyleFamily =
  | "Regular (single) wall"
  | "Thick (heavy) wall"
  | "Double wall — round base"
  | "Double wall — straight base"
  | "Double wall — in-mold frost"
  | "Smooth side & top closure"
  | "Dome closure"
  | "Cosmetic dust cover"
  | "Jar insert"
  | "Program";

export interface Product {
  id: string;
  /** Base item code as published by Taral. */
  code: string;
  name: string;
  category: Category;
  styleFamily: StyleFamily;
  /** Nominal fill volume label, e.g. "1/4 oz". */
  size: string;
  /** Numeric ounces for range filtering. */
  sizeOz: number;
  /** Neck finish, e.g. "33mm-400". Null for non-threaded items. */
  neck: string | null;
  neckDiameterMm: number | null;
  material: string;
  /** Colors / resins Taral lists for this item, with stocking status. */
  materialOptions: { label: string; stocked: boolean }[];
  color: string;
  caseCount: number;
  caseWeightLb: number | null;
  casesPerPallet: number | null;
  freightClass: string | null;
  caseDims: string | null;
  stock: StockStatus;
  /** Non-stock minimum order quantity in pieces, when published. */
  moqEach: number | null;
  /** Mold setup / color purge note, when published. */
  setupNote: string | null;
  /** Lid styles Taral pairs with this jar (from the style comparison chart). */
  lidStyles?: string[];
  /** Invented distributor price for the demo account. Never a real price. */
  demoUnitPrice: number | null;
  quantityBreaks?: { minCases: number; unitPrice: number }[];
  dims?: { height?: string; opening?: string; maxFill?: string };
  availableToSell?: number;
  warehouses?: { code: string; name: string; qty: number }[];
  /** Which parts of the row come from Taral's published documents. */
  source: "published-specs" | "illustrative";
  notes?: string;
}

export const CATEGORIES: Category[] = [
  "Regular Wall Jars",
  "Thick Wall Jars",
  "Double Wall Jars",
  "Lids & Closures",
  "Discs & Dust Covers",
  "Add-ons",
];

export const STOCK_STATUSES: StockStatus[] = ["In stock", "Overrun — call", "Made to order"];

/** Published program-wide rules, quoted for the demo. */
export const PROGRAM_RULES = {
  stockMinimum: "Stock items carry a 1 case minimum, subject to the small order fee.",
  smallOrder: "$300 minimum order excluding freight, or a $50 small order fee.",
  setup: "$350 mold setup / color purge per mold on non-stock items below MOQ.",
  customColor: "Custom color minimum: 25,000 each.",
  pcr: "Post-consumer resin minimum: 25,000 each. Jars up to 100% PCR, closures up to 55%.",
  pallet: "$14.00 per pallet.",
  warehouse: "FOB Corona, CA 92878",
  compliance: "BPA free · PFAS free · no bisphenols · FDA-compliant virgin resin · recyclable",
} as const;

/**
 * Invented pricing. Deliberately synthetic so no confidential figure appears:
 * a flat base plus a coefficient on fill volume, with two demo quantity breaks.
 */
function illustrativePrice(base: number) {
  const round = (n: number) => Math.round(n * 1000) / 1000;
  const unit = round(base);
  return {
    demoUnitPrice: unit,
    quantityBreaks: [
      { minCases: 1, unitPrice: unit },
      { minCases: 5, unitPrice: round(unit * 0.94) },
      { minCases: 20, unitPrice: round(unit * 0.89) },
    ],
  };
}

const jarPrice = (ml: number) => illustrativePrice(0.045 + ml * 0.0034);
const capPrice = (mm: number, lined: boolean) =>
  illustrativePrice(mm * 0.0021 + (lined ? 0.03 : 0));
const discPrice = (mm: number) => illustrativePrice(0.006 + mm * 0.00035);

const OPT = (label: string, stocked: boolean) => ({ label, stocked });

/** Stock status follows the published program: any stocked color ⇒ stock item. */
function statusFor(options: { label: string; stocked: boolean }[]): StockStatus {
  if (options.some((o) => o.stocked)) return "In stock";
  return options.length > 0 ? "Overrun — call" : "Made to order";
}

interface JarSeed {
  id: string;
  code: string;
  size: string;
  sizeOz: number;
  neckMm: number;
  maxFillMl: number;
  diameter: string;
  height: string;
  caseCount: number;
  caseWeightLb: number;
  casesPerPallet: number;
  freightClass: string;
  caseDims: string;
  moqEach: number | null;
  setupNote?: string;
  options: { label: string; stocked: boolean }[];
  notes?: string;
}

const REGULAR_WALL_LIDS = [
  "Ribbed side, matte or smooth top",
  "Smooth side & top",
  "High smooth side & top",
  "Dome cap",
];
const FLUSH_WALL_LIDS = ["Smooth side & top", "Dome cap"];
const DOUBLE_WALL_LIDS = ["Smooth side & top", "High smooth side & top", "Dome cap"];

const REGULAR_WALL: JarSeed[] = [
  {
    id: "rw-quarter-33",
    code: "1/4-33-RW-PPT",
    size: "1/4 oz",
    sizeOz: 0.25,
    neckMm: 33,
    maxFillMl: 14,
    diameter: '1.05"',
    height: '1.13"',
    caseCount: 2000,
    caseWeightLb: 16,
    casesPerPallet: 42,
    freightClass: "125",
    caseDims: '20" x 14" x 14.5"',
    moqEach: 100000,
    options: [OPT("Clarified PP", true), OPT("White PP", true), OPT("Crystal Clear PS", false)],
  },
  {
    id: "rw-half-33",
    code: "1/2-33-PPT",
    size: "1/2 oz",
    sizeOz: 0.5,
    neckMm: 33,
    maxFillMl: 21,
    diameter: '1.07"',
    height: '1.54"',
    caseCount: 1500,
    caseWeightLb: 15.2,
    casesPerPallet: 42,
    freightClass: "125",
    caseDims: '20" x 14" x 14.5"',
    moqEach: 150000,
    setupNote: "150,000 each or $500 setup",
    options: [OPT("Crystal Clear PS", true), OPT("Clarified PP", true), OPT("White PP", false)],
    notes: "Shares a mold with the 7/8 oz 33mm jar.",
  },
  {
    id: "rw-half-38",
    code: "1/2-38-PPT",
    size: "1/2 oz",
    sizeOz: 0.5,
    neckMm: 38,
    maxFillMl: 19,
    diameter: '1.29"',
    height: '1.06"',
    caseCount: 1500,
    caseWeightLb: 16,
    casesPerPallet: 42,
    freightClass: "125",
    caseDims: '20" x 14" x 14.5"',
    moqEach: 35000,
    options: [OPT("White PP", false)],
  },
  {
    id: "rw-half-43",
    code: "1/2-43-PPT",
    size: "1/2 oz",
    sizeOz: 0.5,
    neckMm: 43,
    maxFillMl: 23.5,
    diameter: '1.41"',
    height: '1.09"',
    caseCount: 1300,
    caseWeightLb: 16,
    casesPerPallet: 42,
    freightClass: "125",
    caseDims: '20" x 14" x 14.5"',
    moqEach: 35000,
    options: [OPT("Crystal Clear PS", true)],
  },
  {
    id: "rw-seveneighths-33",
    code: "7/8-33-UL-PPT",
    size: "7/8 oz",
    sizeOz: 0.875,
    neckMm: 33,
    maxFillMl: 25.5,
    diameter: '1.05"',
    height: '1.94"',
    caseCount: 1100,
    caseWeightLb: 14,
    casesPerPallet: 42,
    freightClass: "175",
    caseDims: '20" x 14" x 14.5"',
    moqEach: 150000,
    setupNote: "150,000 each or $500 setup",
    options: [OPT("Clarified PP", true), OPT("Crystal Clear PS", false)],
    notes: "Shares a mold with the 1/2 oz 33mm jar.",
  },
  {
    id: "rw-one-33",
    code: "1-33-PPT",
    size: "1 oz",
    sizeOz: 1,
    neckMm: 33,
    maxFillMl: 34,
    diameter: '1.06"',
    height: '2.66"',
    caseCount: 900,
    caseWeightLb: 15,
    casesPerPallet: 42,
    freightClass: "125",
    caseDims: '20" x 14" x 14.5"',
    moqEach: 25000,
    options: [OPT("Crystal Clear PS", false)],
  },
  {
    id: "rw-one-38",
    code: "1-38-RW-PPT",
    size: "1 oz",
    sizeOz: 1,
    neckMm: 38,
    maxFillMl: 41,
    diameter: '1.28"',
    height: '2.13"',
    caseCount: 700,
    caseWeightLb: 13,
    casesPerPallet: 42,
    freightClass: "125",
    caseDims: '20" x 14" x 14.5"',
    moqEach: 50000,
    options: [
      OPT("Crystal Clear PS", true),
      OPT("Clarified PP", true),
      OPT("White PP", true),
      OPT("Black PP", false),
    ],
  },
  {
    id: "rw-one-43",
    code: "1-43-PPT",
    size: "1 oz",
    sizeOz: 1,
    neckMm: 43,
    maxFillMl: 37.5,
    diameter: '1.43"',
    height: '1.58"',
    caseCount: 800,
    caseWeightLb: 15.5,
    casesPerPallet: 42,
    freightClass: "125",
    caseDims: '20" x 14" x 14.5"',
    moqEach: 35000,
    options: [OPT("Crystal Clear PS", true), OPT("Clarified PP", true), OPT("White PP", true)],
  },
  {
    id: "rw-two-38",
    code: "2-38-PPT",
    size: "2 oz",
    sizeOz: 2,
    neckMm: 38,
    maxFillMl: 59.5,
    diameter: '1.29"',
    height: '2.99"',
    caseCount: 475,
    caseWeightLb: 12,
    casesPerPallet: 42,
    freightClass: "175",
    caseDims: '20" x 14" x 14.5"',
    moqEach: 35000,
    options: [OPT("Black PP", false)],
    notes: "Shares a mold with the 1/2 oz 38mm jar.",
  },
  {
    id: "rw-two-43",
    code: "2-43-PPT",
    size: "2 oz",
    sizeOz: 2,
    neckMm: 43,
    maxFillMl: 64,
    diameter: '1.43"',
    height: '2.65"',
    caseCount: 425,
    caseWeightLb: 14.1,
    casesPerPallet: 42,
    freightClass: "175",
    caseDims: '20" x 14" x 14.5"',
    moqEach: 50000,
    options: [OPT("Clarified PP", true), OPT("White PP", true)],
  },
  {
    id: "rw-two-48",
    code: "2-48-PP",
    size: "2 oz",
    sizeOz: 2,
    neckMm: 48,
    maxFillMl: 79,
    diameter: '1.67"',
    height: '2.35"',
    caseCount: 960,
    caseWeightLb: 25,
    casesPerPallet: 20,
    freightClass: "175",
    caseDims: '20" x 14" x 14.5"',
    moqEach: 50000,
    options: [OPT("Clarified PP", true), OPT("White PP", true)],
  },
  {
    id: "rw-two-53",
    code: "2-53-RW-PP",
    size: "2 oz",
    sizeOz: 2,
    neckMm: 53,
    maxFillMl: 76,
    diameter: '1.86"',
    height: '1.80"',
    caseCount: 910,
    caseWeightLb: 20,
    casesPerPallet: 20,
    freightClass: "175",
    caseDims: '24" x 16" x 20"',
    moqEach: 100000,
    options: [
      OPT("Crystal Clear PS", true),
      OPT("Clarified PP", true),
      OPT("White PP", true),
      OPT("Black PP", false),
    ],
  },
  {
    id: "rw-twohalf-70",
    code: "2.5-70-PPT",
    size: "2.5 oz",
    sizeOz: 2.5,
    neckMm: 70,
    maxFillMl: 101,
    diameter: '2.49"',
    height: '1.38"',
    caseCount: 350,
    caseWeightLb: 13.4,
    casesPerPallet: 42,
    freightClass: "175",
    caseDims: '20" x 14" x 14.5"',
    moqEach: 20000,
    options: [OPT("Clarified PP", true), OPT("White PP", false)],
  },
  {
    id: "rw-four-53",
    code: "4-53-UL-PPT",
    size: "4 oz",
    sizeOz: 4,
    neckMm: 53,
    maxFillMl: 124,
    diameter: '1.84"',
    height: '3.01"',
    caseCount: 450,
    caseWeightLb: 21,
    casesPerPallet: 20,
    freightClass: "175",
    caseDims: '24" x 16" x 20.2"',
    moqEach: 25000,
    options: [
      OPT("Clarified PP", true),
      OPT("White PP", true),
      OPT("Crystal Clear PS", false),
      OPT("Black PP", false),
    ],
    notes: "Shares a mold with the 60 dram 53mm jar.",
  },
  {
    id: "rw-four-70",
    code: "4-70-RW-PP",
    size: "4 oz",
    sizeOz: 4,
    neckMm: 70,
    maxFillMl: 177,
    diameter: '2.52"',
    height: '2.29"',
    caseCount: 560,
    caseWeightLb: 24,
    casesPerPallet: 16,
    freightClass: "175",
    caseDims: '24" x 21" x 20.4"',
    moqEach: 75000,
    options: [
      OPT("Crystal Clear PS", true),
      OPT("Clarified PP", true),
      OPT("White PP", true),
      OPT("Black PP", true),
    ],
  },
  {
    id: "rw-five-53",
    code: "5-53-PPT",
    size: "5 oz",
    sizeOz: 5,
    neckMm: 53,
    maxFillMl: 151,
    diameter: '1.85"',
    height: '3.51"',
    caseCount: 400,
    caseWeightLb: 21,
    casesPerPallet: 20,
    freightClass: "175",
    caseDims: '24" x 16" x 20.2"',
    moqEach: 35000,
    options: [OPT("Crystal Clear PS", false), OPT("Clarified PP", false), OPT("White PP", false)],
    notes: "Newly tooled size.",
  },
  {
    id: "rw-60dram-53",
    code: "60D-53-PP",
    size: "60 dram",
    sizeOz: 6,
    neckMm: 53,
    maxFillMl: 178,
    diameter: '1.84"',
    height: '4.31"',
    caseCount: 520,
    caseWeightLb: 35,
    casesPerPallet: 16,
    freightClass: "125",
    caseDims: '24" x 21" x 20.4"',
    moqEach: 25000,
    options: [OPT("Crystal Clear PS", false), OPT("Black PP", false)],
    notes: 'Listed as "6 oz 53mm". Shares a mold with the 4 oz 53mm jar.',
  },
  {
    id: "rw-six-89",
    code: "6-89-PP",
    size: "6 oz",
    sizeOz: 6,
    neckMm: 89,
    maxFillMl: 240,
    diameter: '3.20"',
    height: '1.97"',
    caseCount: 369,
    caseWeightLb: 28.5,
    casesPerPallet: 16,
    freightClass: "175",
    caseDims: '24" x 21" x 20.4"',
    moqEach: 25000,
    options: [OPT("Clarified PP", true)],
  },
  {
    id: "rw-eight-70",
    code: "8-70-PP",
    size: "8 oz",
    sizeOz: 8,
    neckMm: 70,
    maxFillMl: 269,
    diameter: '2.53"',
    height: '3.45"',
    caseCount: 350,
    caseWeightLb: 22.5,
    casesPerPallet: 16,
    freightClass: "175",
    caseDims: '24" x 21" x 20.4"',
    moqEach: 25000,
    setupNote: "25,000 each (PP) · 15,000 each (PS)",
    options: [OPT("Crystal Clear PS", true), OPT("Clarified PP", true), OPT("White PP", true)],
  },
  {
    id: "rw-eight-89",
    code: "8-89-PP",
    size: "8 oz",
    sizeOz: 8,
    neckMm: 89,
    maxFillMl: 317,
    diameter: '3.24"',
    height: '2.51"',
    caseCount: 287,
    caseWeightLb: 22,
    casesPerPallet: 16,
    freightClass: "250",
    caseDims: '24" x 21" x 20.4"',
    moqEach: 25000,
    options: [
      OPT("Clarified PP", true),
      OPT("White PP", true),
      OPT("Crystal Clear PS", false),
      OPT("Black PP", false),
    ],
  },
  {
    id: "rw-twelve-89",
    code: "12-89-PP",
    size: "12 oz",
    sizeOz: 12,
    neckMm: 89,
    maxFillMl: 397,
    diameter: '3.25"',
    height: '3.15"',
    caseCount: 246,
    caseWeightLb: 25.1,
    casesPerPallet: 16,
    freightClass: "175",
    caseDims: '24" x 21" x 20.4"',
    moqEach: 25000,
    options: [OPT("Clarified PP", true), OPT("White PP", true), OPT("Black PP", false)],
  },
  {
    id: "rw-sixteen-89",
    code: "16-89-RW-PP",
    size: "16 oz",
    sizeOz: 16,
    neckMm: 89,
    maxFillMl: 496,
    diameter: '3.25"',
    height: '3.80"',
    caseCount: 205,
    caseWeightLb: 19,
    casesPerPallet: 16,
    freightClass: "250",
    caseDims: '24" x 21" x 20.4"',
    moqEach: 75000,
    options: [
      OPT("Crystal Clear PS", true),
      OPT("Clarified PP", true),
      OPT("White PP", true),
      OPT("Black PP", true),
    ],
  },
  {
    id: "rw-sixteen-120",
    code: "16-120-PP",
    size: "16 oz",
    sizeOz: 16,
    neckMm: 120,
    maxFillMl: 570,
    diameter: '4.43"',
    height: '2.35"',
    caseCount: 184,
    caseWeightLb: 20,
    casesPerPallet: 16,
    freightClass: "250",
    caseDims: '24" x 21" x 20.4"',
    moqEach: 25000,
    options: [OPT("Clarified PP", false), OPT("Black PP", false)],
  },
  {
    id: "rw-thirtytwo-120",
    code: "32-120-PP",
    size: "32 oz",
    sizeOz: 32,
    neckMm: 120,
    maxFillMl: 925,
    diameter: '4.44"',
    height: '3.80"',
    caseCount: 115,
    caseWeightLb: 18,
    casesPerPallet: 16,
    freightClass: "250",
    caseDims: '24" x 21" x 20.4"',
    moqEach: 25000,
    options: [OPT("Clarified PP", false), OPT("White PP", false)],
  },
];

const THICK_WALL: JarSeed[] = [
  {
    id: "tw-eighth-33",
    code: "1/8-33-TW2-PP",
    size: "1/8 oz",
    sizeOz: 0.125,
    neckMm: 33,
    maxFillMl: 8,
    diameter: '1.37"',
    height: '0.96"',
    caseCount: 1900,
    caseWeightLb: 30,
    casesPerPallet: 42,
    freightClass: "85",
    caseDims: '20" x 14" x 14.5"',
    moqEach: 35000,
    options: [OPT("Crystal Clear PS", true), OPT("Black PP", true), OPT("White PP", false)],
  },
  {
    id: "tw-quarter-33",
    code: "1/4-33-TW2-PPT",
    size: "1/4 oz",
    sizeOz: 0.25,
    neckMm: 33,
    maxFillMl: 15,
    diameter: '1.37"',
    height: '1.17"',
    caseCount: 1400,
    caseWeightLb: 30,
    casesPerPallet: 42,
    freightClass: "85",
    caseDims: '20" x 14" x 14.5"',
    moqEach: 35000,
    options: [OPT("Clarified PP", true), OPT("White PP", true), OPT("Crystal Clear PS", false)],
  },
  {
    id: "tw-half-43",
    code: "1/2-43-TW-PPT",
    size: "1/2 oz",
    sizeOz: 0.5,
    neckMm: 43,
    maxFillMl: 26,
    diameter: '1.75"',
    height: '1.09"',
    caseCount: 950,
    caseWeightLb: 26,
    casesPerPallet: 42,
    freightClass: "92.5",
    caseDims: '20" x 14" x 14.5"',
    moqEach: 35000,
    options: [OPT("Crystal Clear PS", true), OPT("Clarified PP", true)],
  },
  {
    id: "tw-one-43",
    code: "1-43-TW-PP",
    size: "1 oz",
    sizeOz: 1,
    neckMm: 43,
    maxFillMl: 35,
    diameter: '1.74"',
    height: '1.59"',
    caseCount: 728,
    caseWeightLb: 27,
    casesPerPallet: 42,
    freightClass: "92.5",
    caseDims: '20" x 14" x 14.5"',
    moqEach: 50000,
    options: [OPT("Crystal Clear PS", true), OPT("Natural PP", false)],
  },
  {
    id: "tw-one-70",
    code: "1-70-TW-PP",
    size: "1 oz",
    sizeOz: 1,
    neckMm: 70,
    maxFillMl: 62,
    diameter: '2.87"',
    height: '0.93"',
    caseCount: 420,
    caseWeightLb: 23.3,
    casesPerPallet: 42,
    freightClass: "100",
    caseDims: '20" x 14" x 14.5"',
    moqEach: 35000,
    setupNote: "$350 under 35,000 each · $500 under 20,000 each",
    options: [OPT("White PP", false)],
  },
  {
    id: "tw-two-53",
    code: "2-53-TW2-PP",
    size: "2 oz",
    sizeOz: 2,
    neckMm: 53,
    maxFillMl: 75,
    diameter: '2.14"',
    height: '1.80"',
    caseCount: 392,
    caseWeightLb: 22.5,
    casesPerPallet: 42,
    freightClass: "100",
    caseDims: '20" x 14" x 14.5"',
    moqEach: 35000,
    options: [OPT("Crystal Clear PS", true), OPT("Black PP", false)],
  },
  {
    id: "tw-two-70",
    code: "2-70-TW-PP",
    size: "2 oz",
    sizeOz: 2,
    neckMm: 70,
    maxFillMl: 90.5,
    diameter: '2.86"',
    height: '1.29"',
    caseCount: 300,
    caseWeightLb: 21,
    casesPerPallet: 42,
    freightClass: "100",
    caseDims: '20" x 14" x 14.5"',
    moqEach: 35000,
    options: [
      OPT("Crystal Clear PS", true),
      OPT("Clarified PP", true),
      OPT("Natural PP", false),
      OPT("Black PP", false),
    ],
  },
  {
    id: "tw-four-70",
    code: "4-70-TW-PP",
    size: "4 oz",
    sizeOz: 4,
    neckMm: 70,
    maxFillMl: 171,
    diameter: '2.86"',
    height: '2.28"',
    caseCount: 180,
    caseWeightLb: 22,
    casesPerPallet: 42,
    freightClass: "100",
    caseDims: '20" x 14" x 14.5"',
    moqEach: 35000,
    options: [OPT("Crystal Clear PS", true), OPT("Natural PP", false)],
  },
  {
    id: "tw-eight-89",
    code: "8-89-TW-PP",
    size: "8 oz",
    sizeOz: 8,
    neckMm: 89,
    maxFillMl: 315,
    diameter: '3.61"',
    height: '2.53"',
    caseCount: 252,
    caseWeightLb: 43,
    casesPerPallet: 20,
    freightClass: "100",
    caseDims: '24" x 16" x 20.2"',
    moqEach: 25000,
    options: [],
  },
  {
    id: "tw-twelve-89",
    code: "12-89-TW-PP",
    size: "12 oz",
    sizeOz: 12,
    neckMm: 89,
    maxFillMl: 395,
    diameter: '3.59"',
    height: '3.16"',
    caseCount: 180,
    caseWeightLb: 38,
    casesPerPallet: 20,
    freightClass: "100",
    caseDims: '24" x 16" x 20.2"',
    moqEach: 25000,
    options: [OPT("Natural PP", false)],
  },
];

interface DoubleWallSeed extends JarSeed {
  family:
    "Double wall — round base" | "Double wall — straight base" | "Double wall — in-mold frost";
  baseLabel: string;
}

const DOUBLE_WALL: DoubleWallSeed[] = [
  {
    id: "dw-quarter-33-straight",
    code: "1/4-33-DS-PPT",
    family: "Double wall — straight base",
    baseLabel: "straight base",
    size: "1/4 oz",
    sizeOz: 0.25,
    neckMm: 33,
    maxFillMl: 11,
    diameter: '1.38"',
    height: '1.01"',
    caseCount: 1675,
    caseWeightLb: 19.3,
    casesPerPallet: 42,
    freightClass: "100",
    caseDims: '20" x 14" x 14.5"',
    moqEach: 200000,
    setupNote: "200,000 each or $1,600 to set up molds and auto-assembly",
    options: [OPT("White PP/PP", true), OPT("Black PP/PP", true)],
  },
  {
    id: "dw-two-58-round",
    code: "2-58-DR-PP",
    family: "Double wall — round base",
    baseLabel: "round base",
    size: "2 oz",
    sizeOz: 2,
    neckMm: 58,
    maxFillMl: 78,
    diameter: '2.35"',
    height: '1.94"',
    caseCount: 660,
    caseWeightLb: 28,
    casesPerPallet: 20,
    freightClass: "125",
    caseDims: '24" x 16" x 20.2"',
    moqEach: 250000,
    setupNote: "250,000 each or $2,700 to set up molds and auto-assembly",
    options: [OPT("White PP/PP", true), OPT("Black PP/PP", true), OPT("Natural PP/PP", false)],
  },
  {
    id: "dw-two-58-straight",
    code: "2-58-DS-PP",
    family: "Double wall — straight base",
    baseLabel: "straight base",
    size: "2 oz",
    sizeOz: 2,
    neckMm: 58,
    maxFillMl: 78,
    diameter: '2.35"',
    height: '1.94"',
    caseCount: 660,
    caseWeightLb: 30,
    casesPerPallet: 20,
    freightClass: "125",
    caseDims: '24" x 16" x 20.2"',
    moqEach: 250000,
    setupNote: "250,000 each or $2,700 to set up molds and auto-assembly",
    options: [OPT("White PP/PP", true), OPT("Black PP/PP", true), OPT("Natural PP/PP", false)],
  },
  {
    id: "dw-two-58-imf",
    code: "2-58-DS-IMF-PP",
    family: "Double wall — in-mold frost",
    baseLabel: "in-mold frost straight base",
    size: "2 oz",
    sizeOz: 2,
    neckMm: 58,
    maxFillMl: 78,
    diameter: '2.35"',
    height: '1.94"',
    caseCount: 660,
    caseWeightLb: 30,
    casesPerPallet: 20,
    freightClass: "125",
    caseDims: '24" x 16" x 20.2"',
    moqEach: 50000,
    setupNote: "50,000 each or $250 setup",
    options: [],
  },
  {
    id: "dw-four-70-round",
    code: "4-70-DR-PP",
    family: "Double wall — round base",
    baseLabel: "round base",
    size: "4 oz",
    sizeOz: 4,
    neckMm: 70,
    maxFillMl: 150,
    diameter: '2.89"',
    height: '2.42"',
    caseCount: 360,
    caseWeightLb: 30,
    casesPerPallet: 20,
    freightClass: "Call",
    caseDims: '24" x 16" x 20.2"',
    moqEach: 250000,
    setupNote: "250,000 each or $2,100 to set up molds and auto-assembly",
    options: [OPT("White PP/PP", true), OPT("Natural PP/PP", true), OPT("Black PP/PP", true)],
  },
  {
    id: "dw-four-70-straight",
    code: "4-70-DS-PP",
    family: "Double wall — straight base",
    baseLabel: "straight base",
    size: "4 oz",
    sizeOz: 4,
    neckMm: 70,
    maxFillMl: 150,
    diameter: '2.89"',
    height: '2.42"',
    caseCount: 360,
    caseWeightLb: 31,
    casesPerPallet: 20,
    freightClass: "Call",
    caseDims: '24" x 16" x 20.2"',
    moqEach: 250000,
    setupNote: "250,000 each or $2,100 to set up molds and auto-assembly",
    options: [OPT("White PP/PP", true), OPT("Natural PP/PP", true), OPT("Black PP/PP", true)],
  },
  {
    id: "dw-four-70-imf",
    code: "4-70-DS-IMF-PP",
    family: "Double wall — in-mold frost",
    baseLabel: "in-mold frost straight base",
    size: "4 oz",
    sizeOz: 4,
    neckMm: 70,
    maxFillMl: 150,
    diameter: '2.89"',
    height: '2.42"',
    caseCount: 360,
    caseWeightLb: 31,
    casesPerPallet: 20,
    freightClass: "125",
    caseDims: '24" x 16" x 20.2"',
    moqEach: 50000,
    setupNote: "50,000 each or $250 setup",
    options: [],
  },
  {
    id: "dw-eight-89-round",
    code: "8-89-DR-PP",
    family: "Double wall — round base",
    baseLabel: "round base",
    size: "8 oz",
    sizeOz: 8,
    neckMm: 89,
    maxFillMl: 282,
    diameter: '3.66"',
    height: '2.66"',
    caseCount: 245,
    caseWeightLb: 29.4,
    casesPerPallet: 16,
    freightClass: "175",
    caseDims: '24" x 21" x 20.4"',
    moqEach: 150000,
    setupNote: "150,000 each or $1,500 to set up molds and auto-assembly",
    options: [OPT("White PP/PP", true), OPT("Natural PP/PP", true)],
  },
  {
    id: "dw-eight-89-straight",
    code: "8-89-DS-PP",
    family: "Double wall — straight base",
    baseLabel: "straight base",
    size: "8 oz",
    sizeOz: 8,
    neckMm: 89,
    maxFillMl: 282,
    diameter: '3.66"',
    height: '2.66"',
    caseCount: 245,
    caseWeightLb: 30,
    casesPerPallet: 16,
    freightClass: "175",
    caseDims: '24" x 21" x 20.4"',
    moqEach: 150000,
    setupNote: "150,000 each or $1,500 to set up molds and auto-assembly",
    options: [OPT("White PP/PP", true), OPT("Natural PP/PP", true), OPT("Black PP/PP", true)],
  },
];

function jarProduct(
  seed: JarSeed,
  category: Category,
  family: StyleFamily,
  name: string,
  lidStyles: string[],
  diameterLabel: "Opening (inside)" | "Outside diameter",
): Product {
  const options = seed.options;
  const stocked = options.filter((o) => o.stocked);
  const status = statusFor(options);
  const price = jarPrice(seed.maxFillMl);
  return {
    id: seed.id,
    code: seed.code,
    name,
    category,
    styleFamily: family,
    size: seed.size,
    sizeOz: seed.sizeOz,
    neck: `${seed.neckMm}mm-400`,
    neckDiameterMm: seed.neckMm,
    material: options[0]?.label ?? "Polypropylene (PP)",
    materialOptions: options,
    color: stocked[0]?.label ?? options[0]?.label ?? "Quoted per run",
    caseCount: seed.caseCount,
    caseWeightLb: seed.caseWeightLb,
    casesPerPallet: seed.casesPerPallet,
    freightClass: seed.freightClass,
    caseDims: seed.caseDims,
    stock: status,
    moqEach: seed.moqEach,
    setupNote: seed.setupNote ?? null,
    lidStyles,
    ...(status === "In stock" ? price : { demoUnitPrice: null }),
    dims: {
      height: seed.height,
      opening: `${seed.diameter} ${diameterLabel === "Outside diameter" ? "OD" : "ID"}`,
      maxFill: `${seed.maxFillMl} ml`,
    },
    availableToSell:
      status === "In stock" ? seed.caseCount * (seed.casesPerPallet >= 40 ? 34 : 18) : 0,
    warehouses:
      status === "In stock"
        ? [
            {
              code: "CRN",
              name: "Corona, CA",
              qty: seed.caseCount * (seed.casesPerPallet >= 40 ? 34 : 18),
            },
          ]
        : [],
    source: "published-specs",
    ...(seed.notes ? { notes: seed.notes } : {}),
  };
}

interface ClosureSeed {
  id: string;
  code: string;
  neckMm: number;
  style: "Smooth side & top" | "Dome";
  liner: string;
  caseCount: number;
  caseWeightLb: number;
  colors: { label: string; stocked: boolean }[];
}

const CLOSURES: ClosureSeed[] = [
  {
    id: "cap-58ss-unlined",
    code: "58SS-PP-UC",
    neckMm: 58,
    style: "Smooth side & top",
    liner: "Unlined",
    caseCount: 1050,
    caseWeightLb: 17,
    colors: [OPT("Natural PP", true), OPT("White PP", true), OPT("Black PP", true)],
  },
  {
    id: "cap-58ss-foam",
    code: "58SS-PP-FC",
    neckMm: 58,
    style: "Smooth side & top",
    liner: "PE foam (SureSeal 222 / F-217)",
    caseCount: 1050,
    caseWeightLb: 19,
    colors: [OPT("White PP", true), OPT("Black PP", true), OPT("Natural PP", false)],
  },
  {
    id: "cap-70ss-unlined",
    code: "70SS-PP-UC",
    neckMm: 70,
    style: "Smooth side & top",
    liner: "Unlined",
    caseCount: 700,
    caseWeightLb: 16,
    colors: [OPT("Natural PP", true), OPT("White PP", true), OPT("Black PP", true)],
  },
  {
    id: "cap-70ss-foam",
    code: "70SS-PP-FC",
    neckMm: 70,
    style: "Smooth side & top",
    liner: "PE foam (SureSeal 222 / F-217)",
    caseCount: 700,
    caseWeightLb: 18,
    colors: [OPT("Natural PP", true), OPT("White PP", true), OPT("Black PP", true)],
  },
  {
    id: "cap-89ss-unlined",
    code: "89SS-PP-UC",
    neckMm: 89,
    style: "Smooth side & top",
    liner: "Unlined",
    caseCount: 370,
    caseWeightLb: 14.5,
    colors: [OPT("Natural PP", true), OPT("White PP", true), OPT("Black PP", true)],
  },
  {
    id: "cap-89ss-foam",
    code: "89SS-PP-FC",
    neckMm: 89,
    style: "Smooth side & top",
    liner: "PE foam (SureSeal 222 / F-217)",
    caseCount: 370,
    caseWeightLb: 16,
    colors: [OPT("Natural PP", true), OPT("White PP", true), OPT("Black PP", false)],
  },
  {
    id: "cap-70d-unlined",
    code: "70D-PP-UC",
    neckMm: 70,
    style: "Dome",
    liner: "Unlined",
    caseCount: 680,
    caseWeightLb: 16,
    colors: [OPT("Natural PP", true), OPT("White PP", true), OPT("Black PP", true)],
  },
  {
    id: "cap-70d-foam",
    code: "70D-PP-FC",
    neckMm: 70,
    style: "Dome",
    liner: "PE foam (SureSeal 222 / F-217)",
    caseCount: 680,
    caseWeightLb: 18,
    colors: [OPT("Natural PP", true), OPT("White PP", true), OPT("Black PP", true)],
  },
  {
    id: "cap-89d-unlined",
    code: "89D-PP-UC",
    neckMm: 89,
    style: "Dome",
    liner: "Unlined",
    caseCount: 350,
    caseWeightLb: 14.3,
    colors: [OPT("Natural PP", true), OPT("White PP", true), OPT("Black PP", false)],
  },
  {
    id: "cap-89d-foam",
    code: "89D-PP-FC",
    neckMm: 89,
    style: "Dome",
    liner: "PE foam (SureSeal 222 / F-217)",
    caseCount: 350,
    caseWeightLb: 16,
    colors: [OPT("Natural PP", true), OPT("White PP", true)],
  },
];

interface DiscSeed {
  id: string;
  code: string;
  neckMm: number;
  outsideDiameter: string;
  caseCount: number;
  caseWeightLb: number;
  casesPerPallet: number;
  caseDims: string;
  moqEach: number;
  clearStocked: boolean;
}

const DISCS: DiscSeed[] = [
  {
    id: "disc-48",
    code: "48DISC-PET.010",
    neckMm: 48,
    outsideDiameter: '1.76"',
    caseCount: 9000,
    caseWeightLb: 17,
    casesPerPallet: 104,
    caseDims: '20" x 11.5" x 6.5"',
    moqEach: 200000,
    clearStocked: false,
  },
  {
    id: "disc-53",
    code: "53DISC-PET.010",
    neckMm: 53,
    outsideDiameter: '1.95"',
    caseCount: 9000,
    caseWeightLb: 18,
    casesPerPallet: 91,
    caseDims: '20" x 14" x 7"',
    moqEach: 200000,
    clearStocked: false,
  },
  {
    id: "disc-58",
    code: "58DISC-PET.010",
    neckMm: 58,
    outsideDiameter: '2.10"',
    caseCount: 9000,
    caseWeightLb: 19,
    casesPerPallet: 70,
    caseDims: '20" x 14" x 8"',
    moqEach: 150000,
    clearStocked: true,
  },
  {
    id: "disc-70",
    code: "70DISC-PET.010",
    neckMm: 70,
    outsideDiameter: '2.59"',
    caseCount: 9000,
    caseWeightLb: 27,
    casesPerPallet: 54,
    caseDims: '20" x 17" x 10"',
    moqEach: 150000,
    clearStocked: true,
  },
  {
    id: "disc-89",
    code: "89DISC-PET.010",
    neckMm: 89,
    outsideDiameter: '3.36"',
    caseCount: 4500,
    caseWeightLb: 23,
    casesPerPallet: 40,
    caseDims: '19" x 11" x 12"',
    moqEach: 100000,
    clearStocked: false,
  },
];

export const PRODUCTS: Product[] = [
  ...REGULAR_WALL.map((seed) =>
    jarProduct(
      seed,
      "Regular Wall Jars",
      "Regular (single) wall",
      `${seed.size} ${seed.neckMm}mm Regular Wall Jar`,
      REGULAR_WALL_LIDS,
      "Opening (inside)",
    ),
  ),
  ...THICK_WALL.map((seed) =>
    jarProduct(
      seed,
      "Thick Wall Jars",
      "Thick (heavy) wall",
      `${seed.size} ${seed.neckMm}mm Thick Wall Jar`,
      FLUSH_WALL_LIDS,
      "Outside diameter",
    ),
  ),
  ...DOUBLE_WALL.map((seed) =>
    jarProduct(
      seed,
      "Double Wall Jars",
      seed.family,
      `${seed.size} ${seed.neckMm}mm Double Wall Jar — ${seed.baseLabel}`,
      DOUBLE_WALL_LIDS,
      "Outside diameter",
    ),
  ),
  ...CLOSURES.map((seed): Product => {
    const status = statusFor(seed.colors);
    const price = capPrice(seed.neckMm, seed.liner !== "Unlined");
    return {
      id: seed.id,
      code: seed.code,
      name: `${seed.neckMm}mm-400 ${seed.style === "Dome" ? "Dome" : "Smooth Side & Top"} Closure — ${seed.liner.split(" (")[0]}`,
      category: "Lids & Closures",
      styleFamily: seed.style === "Dome" ? "Dome closure" : "Smooth side & top closure",
      size: `${seed.neckMm}mm`,
      sizeOz: 0,
      neck: `${seed.neckMm}mm-400`,
      neckDiameterMm: seed.neckMm,
      material: "Polypropylene (PP), inside-center-gated",
      materialOptions: seed.colors,
      color: seed.colors.find((c) => c.stocked)?.label ?? seed.colors[0]?.label ?? "Quoted",
      caseCount: seed.caseCount,
      caseWeightLb: seed.caseWeightLb,
      casesPerPallet: 42,
      freightClass: "100",
      caseDims: '20" x 14" x 14.5"',
      stock: status,
      moqEach: status === "In stock" ? null : 5000,
      setupNote: null,
      ...(status === "In stock" ? price : { demoUnitPrice: null }),
      dims: { maxFill: "—" },
      availableToSell: status === "In stock" ? seed.caseCount * 40 : 0,
      warehouses:
        status === "In stock"
          ? [{ code: "CRN", name: "Corona, CA", qty: seed.caseCount * 40 }]
          : [],
      source: "published-specs",
      notes: `Liner: ${seed.liner}. Other liners are available to order but not stocked regularly — ask your account executive.`,
    };
  }),
  ...DISCS.map((seed): Product => {
    const colors = [
      OPT('White PET, glossy 0.010"', true),
      OPT("Crystal Clear PET", seed.clearStocked),
    ];
    const price = discPrice(seed.neckMm);
    return {
      id: seed.id,
      code: seed.code,
      name: `${seed.neckMm}mm Cosmetic Dust Cover (Sealing Disc)`,
      category: "Discs & Dust Covers",
      styleFamily: "Cosmetic dust cover",
      size: `${seed.neckMm}mm`,
      sizeOz: 0,
      neck: `${seed.neckMm}mm-400`,
      neckDiameterMm: seed.neckMm,
      material: 'PET, 0.010" thick',
      materialOptions: colors,
      color: seed.clearStocked ? "Crystal Clear PET" : 'White PET, glossy 0.010"',
      caseCount: seed.caseCount,
      caseWeightLb: seed.caseWeightLb,
      casesPerPallet: seed.casesPerPallet,
      freightClass: "70",
      caseDims: seed.caseDims,
      stock: "In stock",
      moqEach: seed.moqEach,
      setupNote: "Non-stock colors: MOQ above, or $1,000 setup fee",
      ...price,
      dims: { opening: `${seed.outsideDiameter} OD`, height: '0.010" thick' },
      availableToSell: seed.caseCount * 30,
      warehouses: [{ code: "CRN", name: "Corona, CA", qty: seed.caseCount * 30 }],
      source: "published-specs",
      notes: `Lays flat on the container below the cap and liner. Discs are stacked 250 per roll.${
        seed.clearStocked ? " Crystal Clear PET is stocked in this size." : ""
      }`,
    };
  }),
  {
    id: "insert-one-48",
    code: "1-48-LPE-Insert",
    name: "1 oz Jar Insert for 48mm Containers",
    category: "Add-ons",
    styleFamily: "Jar insert",
    size: "1 oz",
    sizeOz: 1,
    neck: "48mm-400",
    neckDiameterMm: 48,
    material: "LDPE",
    materialOptions: [OPT("Natural LDPE", true)],
    color: "Natural LDPE",
    caseCount: 1100,
    caseWeightLb: 9.5,
    casesPerPallet: 42,
    freightClass: "250",
    caseDims: '20" x 14" x 14.5"',
    stock: "In stock",
    moqEach: null,
    setupNote: null,
    ...illustrativePrice(0.11),
    dims: { opening: '1.6" ID', height: '1.03"' },
    availableToSell: 33000,
    warehouses: [{ code: "CRN", name: "Corona, CA", qty: 33000 }],
    source: "published-specs",
    notes: "Creates two separate compartments inside one jar.",
  },
  {
    id: "addon-uv-screen-printing",
    code: "UV-SCREEN-PRINT",
    name: "UV Screen Printing — 1, 2 & 3 Colors",
    category: "Add-ons",
    styleFamily: "Program",
    size: "Program",
    sizeOz: 0,
    neck: null,
    neckDiameterMm: null,
    material: "UV-curable inks, in-house one-pass printing",
    materialOptions: [],
    color: "Spot colors, Pantone preferred",
    caseCount: 1,
    caseWeightLb: null,
    casesPerPallet: null,
    freightClass: null,
    caseDims: null,
    stock: "Made to order",
    moqEach: 5000,
    setupNote: "Setup fees and price breaks are quoted per artwork and run length",
    demoUnitPrice: null,
    source: "published-specs",
    notes:
      "Price breaks run from 5,000 to 250,000+ pieces. Artwork must be vector (.AI, .EPS, .PDF, .SVG, .CDR), type no smaller than 4 pt, lines no thinner than 0.5 pt.",
  },
  {
    id: "addon-custom-color",
    code: "CUSTOM-COLOR",
    name: "Custom Color Match Program",
    category: "Add-ons",
    styleFamily: "Program",
    size: "Program",
    sizeOz: 0,
    neck: null,
    neckDiameterMm: null,
    material: "Masterbatch color program",
    materialOptions: [],
    color: "Specified by customer",
    caseCount: 1,
    caseWeightLb: null,
    casesPerPallet: null,
    freightClass: null,
    caseDims: null,
    stock: "Made to order",
    moqEach: 25000,
    setupNote: "$350 setup / purge per mold, waived at 50,000 each",
    demoUnitPrice: null,
    source: "published-specs",
    notes: "Custom color minimum order quantity is 25,000 each.",
  },
  {
    id: "addon-pcr",
    code: "PCR-PROGRAM",
    name: "Post-Consumer Resin (PCR) Program",
    category: "Add-ons",
    styleFamily: "Program",
    size: "Program",
    sizeOz: 0,
    neck: null,
    neckDiameterMm: null,
    material: "Post-consumer polypropylene",
    materialOptions: [],
    color: "Natural, clarified, bright white, reds, yellows (up to 30%)",
    caseCount: 1,
    caseWeightLb: null,
    casesPerPallet: null,
    freightClass: null,
    caseDims: null,
    stock: "Made to order",
    moqEach: 25000,
    setupNote: "$350 setup / purge per mold, waived at 50,000 each",
    demoUnitPrice: null,
    source: "published-specs",
    notes: "Jars can be molded with up to 100% PCR; closures up to 55% PCR.",
  },
];

export const getProduct = (id: string) => PRODUCTS.find((p) => p.id === id);

/** Jar styles and the lid families Taral pairs with them. */
export const LID_PAIRING: { jar: string; lids: string[] }[] = [
  { jar: "Regular (single) wall", lids: REGULAR_WALL_LIDS },
  { jar: "Thick (heavy) wall", lids: FLUSH_WALL_LIDS },
  { jar: "Double wall — straight base", lids: DOUBLE_WALL_LIDS },
  { jar: "Double wall — round base", lids: DOUBLE_WALL_LIDS },
];

/** Common uses published for each jar style. */
export const STYLE_USES: Record<string, string[]> = {
  "Regular (single) wall": [
    "Creams & lotions",
    "Household products",
    "Industrial products",
    "Food",
    "Arts, crafts & hobby",
    "Medical / lab testing",
  ],
  "Thick (heavy) wall": ["Creams & lotions", "Hair care", "Nail salons", "Arts, crafts & hobby"],
  "Double wall — straight base": ["Creams & lotions", "Hair care"],
  "Double wall — round base": ["Creams & lotions", "Hair care"],
};

const isJar = (p: Product) => p.category.includes("Jars");

/**
 * Components that fit a product: matched on thread finish, and on the
 * published lid-to-jar pairing chart for closures.
 */
export const compatibleWith = (product: Product) =>
  PRODUCTS.filter((p) => {
    if (p.id === product.id || p.neck === null || p.neck !== product.neck) return false;
    if (isJar(product)) {
      if (p.category === "Lids & Closures") {
        const allowed = product.lidStyles ?? [];
        return p.styleFamily === "Dome closure"
          ? allowed.includes("Dome cap")
          : allowed.includes("Smooth side & top");
      }
      return p.category === "Discs & Dust Covers" || p.category === "Add-ons";
    }
    return isJar(p);
  });

export const money = (n: number, digits = 2) =>
  `$${n.toLocaleString("en-US", { minimumFractionDigits: digits, maximumFractionDigits: digits })}`;
